version: '2'
linters:
  default: none
  enable:
    # defaults
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # addons
    - gocyclo
    - revive
    - whitespace
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    revive:
      rules:
        # this is not a library project
        - name: exported
          disabled: true
