before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

brews:
  - description: Switch Kubeconfig context in new shell
    homepage: https://github.com/chickenzord/ksw
    folder: Formula
    download_strategy: CurlDownloadStrategy
    license: "MIT"
    custom_block: |
      head do
        url "https://github.com/chickenzord/ksw.git", branch: "main"
        depends_on "go" => :build
      end
    install: |
      if build.head?
        system "go", "build", *std_go_args(ldflags: "-s -w -X main.version={{.Version}}"), "."
      else
        bin.install "ksw"
      end
    repository:
      owner: chickenzord
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^nit:'

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
