version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ksw
    main: .
    binary: ksw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.FullCommit}}
      - -X main.BuildDate={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]
      - goos: linux
        formats: ["tar.gz"]
      - goos: darwin
        formats: ["tar.gz"]

brews:
  - description: Switch Kubeconfig context in new shell
    homepage: https://github.com/chickenzord/ksw
    directory: Formula
    download_strategy: CurlDownloadStrategy
    license: "MIT"
    custom_block: |
      head do
        url "https://github.com/chickenzord/ksw.git", branch: "main"
        depends_on "go" => :build
      end
    install: |
      if build.head?
        system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version={{.Version}} -X main.GitCommit={{.FullCommit}} -X main.BuildDate={{.Date}}"), "."
      else
        bin.install "ksw"
      end
    repository:
      owner: chickenzord
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^nit:'
      - '^chore(.+):'
      - '^build(.+):'
      - Merge pull request
      - Merge branch
  groups:
  - title: Features
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 0
  - title: 'Bug fixes'
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 1
  - title: 'Enhancements'
    regexp: "^.*enhancement[(\\w)]*:+.*$"
    order: 2
  - title: Others
    order: 999

# Release configuration
release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## ksw {{ .Tag }}

    Kubeconfig SWitcher - Switch Kubernetes contexts in isolated shells.

    ### Installation

    **Homebrew:**
    ```bash
    brew install chickenzord/tap/ksw
    ```

    **Go Install:**
    ```bash
    go install github.com/chickenzord/ksw@{{ .Tag }}
    ```

    **Binary Download:**
    Download the binary for your platform from the assets below.
  footer: |
    **Full Changelog**: https://github.com/chickenzord/ksw/compare/{{ .PreviousTag }}...{{ .Tag }}

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
