name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.5

  conventional-commits:
    name: conventional-commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: webiny/action-conventional-commits@v1.4.2
